// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: change_logs.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChangeLog = `-- name: CreateChangeLog :one
INSERT INTO change_logs (entity_type, entity_id, action, before, after, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, entity_type, entity_id, action, before, after, created_at, created_by
`

type CreateChangeLogParams struct {
	EntityType string      `json:"entity_type"`
	EntityID   string      `json:"entity_id"`
	Action     string      `json:"action"`
	Before     []byte      `json:"before"`
	After      []byte      `json:"after"`
	CreatedBy  pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateChangeLog(ctx context.Context, arg CreateChangeLogParams) (ChangeLog, error) {
	row := q.db.QueryRow(ctx, createChangeLog,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.Before,
		arg.After,
		arg.CreatedBy,
	)
	var i ChangeLog
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Before,
		&i.After,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getChangeLogByID = `-- name: GetChangeLogByID :one
SELECT id, entity_type, entity_id, action, before, after, created_at, created_by
FROM change_logs
WHERE id = $1
`

func (q *Queries) GetChangeLogByID(ctx context.Context, id int64) (ChangeLog, error) {
	row := q.db.QueryRow(ctx, getChangeLogByID, id)
	var i ChangeLog
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.Before,
		&i.After,
		&i.CreatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listChangeLogsByAuthor = `-- name: ListChangeLogsByAuthor :many
SELECT id, entity_type, entity_id, action, before, after, created_at, created_by
FROM change_logs
WHERE created_by = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListChangeLogsByAuthorParams struct {
	CreatedBy pgtype.UUID `json:"created_by"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListChangeLogsByAuthor(ctx context.Context, arg ListChangeLogsByAuthorParams) ([]ChangeLog, error) {
	rows, err := q.db.Query(ctx, listChangeLogsByAuthor, arg.CreatedBy, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangeLog
	for rows.Next() {
		var i ChangeLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeLogsByEntityType = `-- name: ListChangeLogsByEntityType :many
SELECT id, entity_type, entity_id, action, before, after, created_at, created_by
FROM change_logs
WHERE entity_type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListChangeLogsByEntityTypeParams struct {
	EntityType string `json:"entity_type"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) ListChangeLogsByEntityType(ctx context.Context, arg ListChangeLogsByEntityTypeParams) ([]ChangeLog, error) {
	rows, err := q.db.Query(ctx, listChangeLogsByEntityType, arg.EntityType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangeLog
	for rows.Next() {
		var i ChangeLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChangeLogsForEntity = `-- name: ListChangeLogsForEntity :many
SELECT id, entity_type, entity_id, action, before, after, created_at, created_by
FROM change_logs
WHERE entity_type = $1
  AND entity_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListChangeLogsForEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

// История изменений конкретной сущности — лента "что менялось у этого
// долга / пересдачи / роли". Используется при выводе story-страницы.
func (q *Queries) ListChangeLogsForEntity(ctx context.Context, arg ListChangeLogsForEntityParams) ([]ChangeLog, error) {
	rows, err := q.db.Query(ctx, listChangeLogsForEntity,
		arg.EntityType,
		arg.EntityID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChangeLog
	for rows.Next() {
		var i ChangeLog
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentChangeLogs = `-- name: ListRecentChangeLogs :many
SELECT
    cl.id, cl.entity_type, cl.entity_id, cl.action, cl.before, cl.after, cl.created_at, cl.created_by,
    u.last_name   AS subject_last_name,
    u.first_name  AS subject_first_name,
    u.middle_name AS subject_middle_name
FROM change_logs cl
LEFT JOIN users u ON cl.entity_type = 'user' AND u.id = cl.entity_id::uuid
WHERE cl.entity_type IN ('user', 'role', 'permission')
  AND NOT (cl.entity_type = 'role' AND cl.action IN ('role_assigned', 'role_revoked'))
ORDER BY cl.created_at DESC
LIMIT $1 OFFSET $2
`

type ListRecentChangeLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListRecentChangeLogsRow struct {
	ID                int64              `json:"id"`
	EntityType        string             `json:"entity_type"`
	EntityID          string             `json:"entity_id"`
	Action            string             `json:"action"`
	Before            []byte             `json:"before"`
	After             []byte             `json:"after"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	SubjectLastName   *string            `json:"subject_last_name"`
	SubjectFirstName  *string            `json:"subject_first_name"`
	SubjectMiddleName *string            `json:"subject_middle_name"`
}

// Общий журнал последних изменений для админ-вкладки «Журнал изменений».
// Только сущности users/roles/permissions (доменные debt/retake/discipline
// сюда не тянем — это техника, не для человека). Зеркальные role-side
// записи смены роли скрыты (операция видна со стороны пользователя).
// К user-записям подтягиваем ФИО, чтобы лента читалась без UUID.
func (q *Queries) ListRecentChangeLogs(ctx context.Context, arg ListRecentChangeLogsParams) ([]ListRecentChangeLogsRow, error) {
	rows, err := q.db.Query(ctx, listRecentChangeLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentChangeLogsRow
	for rows.Next() {
		var i ListRecentChangeLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.SubjectLastName,
			&i.SubjectFirstName,
			&i.SubjectMiddleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
