// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	IsRevoked  bool               `json:"is_revoked"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	IpAddress  *string            `json:"ip_address"`
}

type AuditLog struct {
	ID         pgtype.UUID        `json:"id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	Action     string             `json:"action"`
	TargetType string             `json:"target_type"`
	TargetID   *string            `json:"target_id"`
	Details    []byte             `json:"details"`
	IpAddress  *string            `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ChangeLog struct {
	ID         int64              `json:"id"`
	EntityType string             `json:"entity_type"`
	EntityID   string             `json:"entity_id"`
	Action     string             `json:"action"`
	Before     []byte             `json:"before"`
	After      []byte             `json:"after"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	CreatedBy  pgtype.UUID        `json:"created_by"`
}

type Debt struct {
	ID           pgtype.UUID        `json:"id"`
	StudentID    pgtype.UUID        `json:"student_id"`
	DisciplineID pgtype.UUID        `json:"discipline_id"`
	IssuedBy     pgtype.UUID        `json:"issued_by"`
	Status       string             `json:"status"`
	FinalGrade   *int32             `json:"final_grade"`
	GradedAt     pgtype.Timestamptz `json:"graded_at"`
	GradedBy     pgtype.UUID        `json:"graded_by"`
	ExternalID   *string            `json:"external_id"`
	Source       string             `json:"source"`
	Notes        *string            `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.UUID        `json:"deleted_by"`
}

type Discipline struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Code        string             `json:"code"`
	Description *string            `json:"description"`
	ExternalID  *string            `json:"external_id"`
	Source      string             `json:"source"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy   pgtype.UUID        `json:"deleted_by"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Kind      string             `json:"kind"`
	Payload   []byte             `json:"payload"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Permission struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description *string            `json:"description"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy   pgtype.UUID        `json:"deleted_by"`
}

type PermissionRole struct {
	ID           pgtype.UUID        `json:"id"`
	RoleID       pgtype.UUID        `json:"role_id"`
	PermissionID pgtype.UUID        `json:"permission_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.UUID        `json:"deleted_by"`
}

type RefreshToken struct {
	ID            pgtype.UUID        `json:"id"`
	AccessTokenID pgtype.UUID        `json:"access_token_id"`
	TokenHash     string             `json:"token_hash"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	IsUsed        bool               `json:"is_used"`
	IsRevoked     bool               `json:"is_revoked"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Retake struct {
	ID              pgtype.UUID        `json:"id"`
	DisciplineID    pgtype.UUID        `json:"discipline_id"`
	Kind            string             `json:"kind"`
	MinTeachers     int32              `json:"min_teachers"`
	Building        string             `json:"building"`
	Room            string             `json:"room"`
	ScheduledAt     pgtype.Timestamptz `json:"scheduled_at"`
	DurationMinutes int32              `json:"duration_minutes"`
	Status          string             `json:"status"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	Notes           *string            `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy       pgtype.UUID        `json:"deleted_by"`
}

type RetakeChangeRequest struct {
	ID               pgtype.UUID        `json:"id"`
	RetakeID         pgtype.UUID        `json:"retake_id"`
	RequestedBy      pgtype.UUID        `json:"requested_by"`
	RequestedChanges []byte             `json:"requested_changes"`
	Reason           *string            `json:"reason"`
	Status           string             `json:"status"`
	ReviewedBy       pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	DecisionReason   *string            `json:"decision_reason"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RetakeParticipant struct {
	ID        pgtype.UUID        `json:"id"`
	RetakeID  pgtype.UUID        `json:"retake_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Kind      string             `json:"kind"`
	DebtID    pgtype.UUID        `json:"debt_id"`
	Grade     *int32             `json:"grade"`
	GradedAt  pgtype.Timestamptz `json:"graded_at"`
	GradedBy  pgtype.UUID        `json:"graded_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RetakeRequest struct {
	ID              pgtype.UUID        `json:"id"`
	RequestedBy     pgtype.UUID        `json:"requested_by"`
	Payload         []byte             `json:"payload"`
	Status          string             `json:"status"`
	ReviewedBy      pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	DecisionReason  *string            `json:"decision_reason"`
	CreatedRetakeID pgtype.UUID        `json:"created_retake_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description *string            `json:"description"`
	Level       int32              `json:"level"`
	IsSystem    bool               `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy   pgtype.UUID        `json:"deleted_by"`
}

type RoleUser struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy pgtype.UUID        `json:"deleted_by"`
}

type StatementSheet struct {
	ID         pgtype.UUID        `json:"id"`
	RetakeID   pgtype.UUID        `json:"retake_id"`
	Status     string             `json:"status"`
	ClosedAt   pgtype.Timestamptz `json:"closed_at"`
	ClosedBy   pgtype.UUID        `json:"closed_by"`
	ReopenedAt pgtype.Timestamptz `json:"reopened_at"`
	ReopenedBy pgtype.UUID        `json:"reopened_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type StudentDiscipline struct {
	ID           pgtype.UUID        `json:"id"`
	StudentID    pgtype.UUID        `json:"student_id"`
	DisciplineID pgtype.UUID        `json:"discipline_id"`
	AcademicYear *string            `json:"academic_year"`
	Semester     *int32             `json:"semester"`
	Source       string             `json:"source"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type SyncState struct {
	Key          string             `json:"key"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
}

type TeacherDiscipline struct {
	ID           pgtype.UUID        `json:"id"`
	TeacherID    pgtype.UUID        `json:"teacher_id"`
	DisciplineID pgtype.UUID        `json:"discipline_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy    pgtype.UUID        `json:"deleted_by"`
}

type TeacherRoleRequest struct {
	ID             pgtype.UUID        `json:"id"`
	RequestedBy    pgtype.UUID        `json:"requested_by"`
	Reason         *string            `json:"reason"`
	Status         string             `json:"status"`
	ReviewedBy     pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt     pgtype.Timestamptz `json:"reviewed_at"`
	DecisionReason *string            `json:"decision_reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	MiddleName   *string            `json:"middle_name"`
	Birthday     pgtype.Date        `json:"birthday"`
	GroupName    *string            `json:"group_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ExternalID   *string            `json:"external_id"`
}

type UserPhoto struct {
	ID                  int64              `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	OriginalName        string             `json:"original_name"`
	Description         *string            `json:"description"`
	Format              string             `json:"format"`
	SizeBytes           int32              `json:"size_bytes"`
	Width               int32              `json:"width"`
	Height              int32              `json:"height"`
	OriginalContent     []byte             `json:"original_content"`
	OriginalContentType string             `json:"original_content_type"`
	AvatarContent       []byte             `json:"avatar_content"`
	AvatarContentType   string             `json:"avatar_content_type"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}
