// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_photos.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveUserAvatar = `-- name: GetActiveUserAvatar :one
SELECT avatar_content, avatar_content_type, updated_at
FROM user_photos
WHERE user_id = $1 AND deleted_at IS NULL
`

type GetActiveUserAvatarRow struct {
	AvatarContent     []byte             `json:"avatar_content"`
	AvatarContentType string             `json:"avatar_content_type"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Байты квадратной миниатюры 128×128 для публичной отдачи в <img>.
func (q *Queries) GetActiveUserAvatar(ctx context.Context, userID pgtype.UUID) (GetActiveUserAvatarRow, error) {
	row := q.db.QueryRow(ctx, getActiveUserAvatar, userID)
	var i GetActiveUserAvatarRow
	err := row.Scan(&i.AvatarContent, &i.AvatarContentType, &i.UpdatedAt)
	return i, err
}

const getActiveUserOriginal = `-- name: GetActiveUserOriginal :one
SELECT original_content, original_content_type, original_name, format
FROM user_photos
WHERE user_id = $1 AND deleted_at IS NULL
`

type GetActiveUserOriginalRow struct {
	OriginalContent     []byte `json:"original_content"`
	OriginalContentType string `json:"original_content_type"`
	OriginalName        string `json:"original_name"`
	Format              string `json:"format"`
}

// Байты сжатого оригинала для защищённого скачивания владельцем.
func (q *Queries) GetActiveUserOriginal(ctx context.Context, userID pgtype.UUID) (GetActiveUserOriginalRow, error) {
	row := q.db.QueryRow(ctx, getActiveUserOriginal, userID)
	var i GetActiveUserOriginalRow
	err := row.Scan(
		&i.OriginalContent,
		&i.OriginalContentType,
		&i.OriginalName,
		&i.Format,
	)
	return i, err
}

const getActiveUserPhotoMeta = `-- name: GetActiveUserPhotoMeta :one
SELECT id, user_id, original_name, description, format, size_bytes, width, height,
       original_content_type, avatar_content_type, created_at, updated_at
FROM user_photos
WHERE user_id = $1 AND deleted_at IS NULL
`

type GetActiveUserPhotoMetaRow struct {
	ID                  int64              `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	OriginalName        string             `json:"original_name"`
	Description         *string            `json:"description"`
	Format              string             `json:"format"`
	SizeBytes           int32              `json:"size_bytes"`
	Width               int32              `json:"width"`
	Height              int32              `json:"height"`
	OriginalContentType string             `json:"original_content_type"`
	AvatarContentType   string             `json:"avatar_content_type"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// Метаданные активной фотографии (для GET /api/photo). Без bytea.
func (q *Queries) GetActiveUserPhotoMeta(ctx context.Context, userID pgtype.UUID) (GetActiveUserPhotoMetaRow, error) {
	row := q.db.QueryRow(ctx, getActiveUserPhotoMeta, userID)
	var i GetActiveUserPhotoMetaRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalName,
		&i.Description,
		&i.Format,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.OriginalContentType,
		&i.AvatarContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveUserPhotoVersion = `-- name: GetActiveUserPhotoVersion :one
SELECT updated_at
FROM user_photos
WHERE user_id = $1 AND deleted_at IS NULL
`

// Лёгкая проверка наличия + версия (updated_at) для cache-busting в /me.
// Не выгружает байты.
func (q *Queries) GetActiveUserPhotoVersion(ctx context.Context, userID pgtype.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getActiveUserPhotoVersion, userID)
	var updated_at pgtype.Timestamptz
	err := row.Scan(&updated_at)
	return updated_at, err
}

const insertUserPhoto = `-- name: InsertUserPhoto :one

INSERT INTO user_photos (
    user_id, original_name, description, format, size_bytes, width, height,
    original_content, original_content_type, avatar_content, avatar_content_type
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, original_name, description, format, size_bytes, width, height,
          original_content_type, avatar_content_type, created_at, updated_at, deleted_at
`

type InsertUserPhotoParams struct {
	UserID              pgtype.UUID `json:"user_id"`
	OriginalName        string      `json:"original_name"`
	Description         *string     `json:"description"`
	Format              string      `json:"format"`
	SizeBytes           int32       `json:"size_bytes"`
	Width               int32       `json:"width"`
	Height              int32       `json:"height"`
	OriginalContent     []byte      `json:"original_content"`
	OriginalContentType string      `json:"original_content_type"`
	AvatarContent       []byte      `json:"avatar_content"`
	AvatarContentType   string      `json:"avatar_content_type"`
}

type InsertUserPhotoRow struct {
	ID                  int64              `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	OriginalName        string             `json:"original_name"`
	Description         *string            `json:"description"`
	Format              string             `json:"format"`
	SizeBytes           int32              `json:"size_bytes"`
	Width               int32              `json:"width"`
	Height              int32              `json:"height"`
	OriginalContentType string             `json:"original_content_type"`
	AvatarContentType   string             `json:"avatar_content_type"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

// Запросы к user_photos. Метаданные (без bytea) отдаются лёгкими
// SELECT'ами; тяжёлые original_content / avatar_content тянем только
// там, где реально нужно отдать байты клиенту.
// Создаёт новую активную фотографию. RETURNING без bytea — не гоняем
// блобы обратно после вставки.
func (q *Queries) InsertUserPhoto(ctx context.Context, arg InsertUserPhotoParams) (InsertUserPhotoRow, error) {
	row := q.db.QueryRow(ctx, insertUserPhoto,
		arg.UserID,
		arg.OriginalName,
		arg.Description,
		arg.Format,
		arg.SizeBytes,
		arg.Width,
		arg.Height,
		arg.OriginalContent,
		arg.OriginalContentType,
		arg.AvatarContent,
		arg.AvatarContentType,
	)
	var i InsertUserPhotoRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OriginalName,
		&i.Description,
		&i.Format,
		&i.SizeBytes,
		&i.Width,
		&i.Height,
		&i.OriginalContentType,
		&i.AvatarContentType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveUserPhotosForArchive = `-- name: ListActiveUserPhotosForArchive :many
SELECT
    up.id, up.user_id, up.original_name, up.format, up.size_bytes,
    up.original_content, up.original_content_type,
    up.avatar_content, up.avatar_content_type, up.created_at,
    u.email, u.first_name, u.last_name, u.middle_name, u.group_name
FROM user_photos up
JOIN users u ON u.id = up.user_id
WHERE up.deleted_at IS NULL
ORDER BY u.last_name, u.first_name, up.id
`

type ListActiveUserPhotosForArchiveRow struct {
	ID                  int64              `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	OriginalName        string             `json:"original_name"`
	Format              string             `json:"format"`
	SizeBytes           int32              `json:"size_bytes"`
	OriginalContent     []byte             `json:"original_content"`
	OriginalContentType string             `json:"original_content_type"`
	AvatarContent       []byte             `json:"avatar_content"`
	AvatarContentType   string             `json:"avatar_content_type"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	Email               string             `json:"email"`
	FirstName           string             `json:"first_name"`
	LastName            string             `json:"last_name"`
	MiddleName          *string            `json:"middle_name"`
	GroupName           *string            `json:"group_name"`
}

// Все активные фотографии с данными владельца — для админского архива.
// Мягко удалённые исключены (deleted_at IS NULL).
func (q *Queries) ListActiveUserPhotosForArchive(ctx context.Context) ([]ListActiveUserPhotosForArchiveRow, error) {
	rows, err := q.db.Query(ctx, listActiveUserPhotosForArchive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveUserPhotosForArchiveRow
	for rows.Next() {
		var i ListActiveUserPhotosForArchiveRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalName,
			&i.Format,
			&i.SizeBytes,
			&i.OriginalContent,
			&i.OriginalContentType,
			&i.AvatarContent,
			&i.AvatarContentType,
			&i.CreatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveUserPhotosMeta = `-- name: ListAllActiveUserPhotosMeta :many
SELECT
    up.id, up.user_id, up.original_name, up.description, up.format,
    up.size_bytes, up.width, up.height, up.created_at,
    u.email, u.first_name, u.last_name, u.middle_name, u.group_name
FROM user_photos up
JOIN users u ON u.id = up.user_id
WHERE up.deleted_at IS NULL
ORDER BY u.last_name, u.first_name, up.id
`

type ListAllActiveUserPhotosMetaRow struct {
	ID           int64              `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	OriginalName string             `json:"original_name"`
	Description  *string            `json:"description"`
	Format       string             `json:"format"`
	SizeBytes    int32              `json:"size_bytes"`
	Width        int32              `json:"width"`
	Height       int32              `json:"height"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Email        string             `json:"email"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	MiddleName   *string            `json:"middle_name"`
	GroupName    *string            `json:"group_name"`
}

// Метаданные всех активных фотографий (без bytea) с данными владельца —
// для админского просмотра «все фото». Мягко удалённые исключены.
func (q *Queries) ListAllActiveUserPhotosMeta(ctx context.Context) ([]ListAllActiveUserPhotosMetaRow, error) {
	rows, err := q.db.Query(ctx, listAllActiveUserPhotosMeta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllActiveUserPhotosMetaRow
	for rows.Next() {
		var i ListAllActiveUserPhotosMetaRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.OriginalName,
			&i.Description,
			&i.Format,
			&i.SizeBytes,
			&i.Width,
			&i.Height,
			&i.CreatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.MiddleName,
			&i.GroupName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteActiveUserPhoto = `-- name: SoftDeleteActiveUserPhoto :exec
UPDATE user_photos
SET deleted_at = NOW(), updated_at = NOW()
WHERE user_id = $1 AND deleted_at IS NULL
`

// Помечает текущую активную фотографию пользователя удалённой. Вызывается
// и при явном удалении, и перед вставкой новой (чтобы активная осталась одна).
func (q *Queries) SoftDeleteActiveUserPhoto(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteActiveUserPhoto, userID)
	return err
}
