// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_avatars.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserAvatar = `-- name: DeleteUserAvatar :exec
DELETE FROM user_avatars WHERE user_id = $1
`

func (q *Queries) DeleteUserAvatar(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserAvatar, userID)
	return err
}

const getUserAvatar = `-- name: GetUserAvatar :one
SELECT content, content_type, updated_at
FROM user_avatars
WHERE user_id = $1
`

type GetUserAvatarRow struct {
	Content     []byte             `json:"content"`
	ContentType string             `json:"content_type"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserAvatar(ctx context.Context, userID pgtype.UUID) (GetUserAvatarRow, error) {
	row := q.db.QueryRow(ctx, getUserAvatar, userID)
	var i GetUserAvatarRow
	err := row.Scan(&i.Content, &i.ContentType, &i.UpdatedAt)
	return i, err
}

const getUserAvatarMeta = `-- name: GetUserAvatarMeta :one
SELECT content_type, updated_at
FROM user_avatars
WHERE user_id = $1
`

type GetUserAvatarMetaRow struct {
	ContentType string             `json:"content_type"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Лёгкая проверка наличия + версия (updated_at) без выгрузки байтов.
func (q *Queries) GetUserAvatarMeta(ctx context.Context, userID pgtype.UUID) (GetUserAvatarMetaRow, error) {
	row := q.db.QueryRow(ctx, getUserAvatarMeta, userID)
	var i GetUserAvatarMetaRow
	err := row.Scan(&i.ContentType, &i.UpdatedAt)
	return i, err
}

const upsertUserAvatar = `-- name: UpsertUserAvatar :exec
INSERT INTO user_avatars (user_id, content, content_type, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (user_id) DO UPDATE
SET content = EXCLUDED.content,
    content_type = EXCLUDED.content_type,
    updated_at = NOW()
`

type UpsertUserAvatarParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Content     []byte      `json:"content"`
	ContentType string      `json:"content_type"`
}

func (q *Queries) UpsertUserAvatar(ctx context.Context, arg UpsertUserAvatarParams) error {
	_, err := q.db.Exec(ctx, upsertUserAvatar, arg.UserID, arg.Content, arg.ContentType)
	return err
}
