# @baseUrl = http://127.0.0.1:8000
@baseUrl = http://localhost:8000

### 1. Логин Администратора
# @name loginAdmin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json
User-Agent: Admin.http

{
    "username": "AdminMaster",
    "password": "Password_1!"
}

@adminToken = {{loginAdmin.response.body.access_token}}









### УПРАВЛЕНИЕ РОЛЯМИ

### 2. Успешный просмотр всех ролей
GET {{baseUrl}}/api/ref/policy/role
Authorization: Bearer {{adminToken}}

### 3. Создание новой роли "Контент-менеджер"
POST {{baseUrl}}/api/ref/policy/role
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Контент-менеджер",
    "slug": "content_manager",
    "description": "Может писать статьи"
}

### 4. Обновление роли (Например, роль ID = 4)
PUT {{baseUrl}}/api/ref/policy/role/4
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Старший Контент-менеджер",
    "slug": "senior_content_manager"
}



### ЦИКЛ МЯГКОГО УДАЛЕНИЯ 

### 5. Мягкое удаление роли (Улетает в корзину, проставляется deleted_by)
DELETE {{baseUrl}}/api/ref/policy/role/4/soft
Authorization: Bearer {{adminToken}}

### 6. Проверка: роль должна исчезнуть из общего списка
GET {{baseUrl}}/api/ref/policy/role
Authorization: Bearer {{adminToken}}

### 7. Восстановление роли из корзины
POST {{baseUrl}}/api/ref/policy/role/4/restore
Authorization: Bearer {{adminToken}}

### 8. Жесткое удаление (Стираем из БД навсегда)
DELETE {{baseUrl}}/api/ref/policy/role/4
Authorization: Bearer {{adminToken}}