@baseUrl = http://localhost:8000
//@baseUrl = http://127.0.0.1:8000

### 1.1 Регистрация Первого юзера (Он получит ID = 1)
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "username": "AdminMaster",
    "email": "admin@yugu.ru",
    "password": "Password_1!",
    "c_password": "Password_1!",
    "birthday": "1995-05-15"
}

### 1.1.5 Делаем его админом
GET {{baseUrl}}/info/make-me-admin

### 1.2 Логин Админа
# @name loginAdmin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json
User-Agent: VSCode-REST-Client/1.0

{
    "username": "AdminMaster",
    "password": "Password_1!"
}

@adminToken = {{loginAdmin.response.body.access_token}}

### 1.3 Регистрация Обычного юзера
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "username": "JustUser",
    "email": "user@yugu.ru",
    "password": "Password_1!",
    "c_password": "Password_1!",
    "birthday": "2000-01-01"
}

### 1.4 Логин Юзера
# @name loginUser
POST {{baseUrl}}/api/auth/login
Content-Type: application/json
User-Agent: Auth.http

{
    "username": "JustUser",
    "password": "Password_1!"
}

@userToken = {{loginUser.response.body.access_token}}






### 2.1 [ОТКАЗ] Юзер смотрит список ролей
GET {{baseUrl}}/api/ref/policy/role
Authorization: Bearer {{userToken}}

### 2.2 [УСПЕХ] Админ смотрит список ролей (200 OK)
GET {{baseUrl}}/api/ref/policy/role
Authorization: Bearer {{adminToken}}






### БЛОК 3: УПРАВЛЕНИЕ РОЛЯМИ (CRUD)

### 3.1 Создать новую роль "Модератор"
POST {{baseUrl}}/api/ref/policy/role
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Модератор",
    "slug": "moderator",
    "description": "Может банить пользователей"
}

### 3.2 Изменить роль
PUT {{baseUrl}}/api/ref/policy/role/4
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Старший Модератор",
    "slug": "senior_moderator"
}

### 3.3 Мягкое удаление роли (Отправка в корзину)
DELETE {{baseUrl}}/api/ref/policy/role/4/soft
Authorization: Bearer {{adminToken}}

### 3.4 Восстановление мягко удаленной роли
POST {{baseUrl}}/api/ref/policy/role/4/restore
Authorization: Bearer {{adminToken}}

### 3.5 Жесткое удаление роли
DELETE {{baseUrl}}/api/ref/policy/role/4
Authorization: Bearer {{adminToken}}





### БЛОК 4: ВЫДАЧА РОЛЕЙ ПОЛЬЗОВАТЕЛЯМ

### 4.1 Посмотреть роли пользователя
GET {{baseUrl}}/api/ref/user/2/role
Authorization: Bearer {{adminToken}}

### 4.2 Назначить роль пользователю
POST {{baseUrl}}/api/ref/user/2/role
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "role_id": 2
}

### 4.3 Мягко забрать роль у пользователя (Удаляем связь)
DELETE {{baseUrl}}/api/ref/user/2/role/2/soft
Authorization: Bearer {{adminToken}}

### 4.4 Вернуть (восстановить) роль пользователю
POST {{baseUrl}}/api/ref/user/2/role/2/restore
Authorization: Bearer {{adminToken}}

### 4.5 Жестко забрать роль у пользователя навсегда
DELETE {{baseUrl}}/api/ref/user/2/role/2
Authorization: Bearer {{adminToken}}





### БЛОК 5: УПРАВЛЕНИЕ РАЗРЕШЕНИЯМИ (Permissions)

### 5.1 Получить список всех разрешений
GET {{baseUrl}}/api/ref/policy/permission
Authorization: Bearer {{adminToken}}

### 5.2 Создать новое разрешение (Например, для комментариев)
POST {{baseUrl}}/api/ref/policy/permission
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Удалить комментарий",
    "slug": "delete-comment",
    "description": "Позволяет удалять чужие комментарии"
}

### 5.3 Привязать разрешение к роли (Даем "ключ" роли)
POST {{baseUrl}}/api/ref/policy/role/2/permission
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "permission_id": 7
}