@baseUrl = http://localhost:8000
//@baseUrl = http://127.0.0.1:8000



### БЛОК 1: ПОДГОТОВКА И РЕГИСТРАЦИЯ
### 1.1 Регистрация Первого юзера (Он получит ID = 1)
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "username": "AdminMaster",
    "email": "admin@yugu.ru",
    "password": "Password_1!",
    "c_password": "Password_1!",
    "birthday": "1995-05-15"
}

### 1.2 Делаем его админом (Чит-код)
GET {{baseUrl}}/info/make-me-admin

### 1.3 Логин Админа (Сохраняем токен)
# @name loginAdmin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json
User-Agent: VSCode-REST-Client/1.0

{
    "username": "AdminMaster",
    "password": "Password_1!"
}

@adminToken = {{loginAdmin.response.body.access_token}}

### 1.4 Регистрация Обычного юзера (Получит ID = 2)
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
    "username": "JustUser",
    "email": "user@yugu.ru",
    "password": "Password_1!",
    "c_password": "Password_1!",
    "birthday": "2000-01-01"
}

### 1.5 Логин Юзера (Сохраняем токен)
# @name loginUser
POST {{baseUrl}}/api/auth/login
Content-Type: application/json
User-Agent: Auth.http

{
    "username": "JustUser",
    "password": "Password_1!"
}

@userToken = {{loginUser.response.body.access_token}}





### БЛОК 2: ПРОСМОТР СВОИХ ПРАВ
### 2.1 Юзер смотрит СВОИ разрешения
GET {{baseUrl}}/api/auth/me/permissions
Authorization: Bearer {{userToken}}

### 2.1.2 Юзер смотрит СВОИ роли
GET {{baseUrl}}/api/auth/me/roles
Authorization: Bearer {{userToken}}

### 2.2 [ОТКАЗ] Юзер пытается посмотреть чужие/системные роли 
GET {{baseUrl}}/api/ref/policy/role
Authorization: Bearer {{userToken}}

### 2.3 [УСПЕХ] Админ смотрит системные роли
GET {{baseUrl}}/api/ref/policy/role
Authorization: Bearer {{adminToken}}





### БЛОК 3: УПРАВЛЕНИЕ РОЛЯМИ (CRUD)
### 3.1 Создать новую роль "Модератор" (Получит ID = 4)
POST {{baseUrl}}/api/ref/policy/role
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Модератор",
    "slug": "moderator",
    "description": "Может банить пользователей"
}

### 3.2 Создать новую роль "Редактор" (Получит ID = 5)
POST {{baseUrl}}/api/ref/policy/role
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Редактор",
    "slug": "editor",
    "description": "Может писать статьи"
}

### 3.3 Изменить роль Редактора
PUT {{baseUrl}}/api/ref/policy/role/5
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Главный Редактор",
    "slug": "chief_editor"
}





### БЛОК 4: МАССОВАЯ ВЫДАЧА РОЛЕЙ И ЗАЩИТА ОТ ДУБЛЕЙ
### 4.1 Посмотреть текущие роли пользователя 2
GET {{baseUrl}}/api/ref/user/2/role
Authorization: Bearer {{adminToken}}

### 4.2 МАССОВАЯ выдача ролей + Проверка на дубли
POST {{baseUrl}}/api/ref/user/2/role
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "role_ids": [4, 4, 5]
}

### 4.3 Снова смотрим роли пользователя 2
GET {{baseUrl}}/api/ref/user/2/role
Authorization: Bearer {{adminToken}}

### 4.4 Мягко забрать роль (ID=4) у пользователя 
DELETE {{baseUrl}}/api/ref/user/2/role/4/soft
Authorization: Bearer {{adminToken}}

### 4.5 Вернуть (восстановить) роль пользователю
POST {{baseUrl}}/api/ref/user/2/role/4/restore
Authorization: Bearer {{adminToken}}





### БЛОК 5: УПРАВЛЕНИЕ РАЗРЕШЕНИЯМИ (Permissions)
### 5.1 Получить список всех разрешений в системе
GET {{baseUrl}}/api/ref/policy/permission
Authorization: Bearer {{adminToken}}

### 5.2 Создать новое разрешение (Например, для комментариев)
POST {{baseUrl}}/api/ref/policy/permission
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Удалить комментарий",
    "slug": "delete-comment",
    "description": "Позволяет удалять чужие комментарии"
}

### 5.3 Привязать разрешение к роли Модератора (ID=4)
POST {{baseUrl}}/api/ref/policy/role/4/permission
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "permission_id": 7
}

### 5.4 Проверка
GET {{baseUrl}}/api/auth/me/permissions
Authorization: Bearer {{userToken}}





### БЛОК 6: БЕЗОПАСНОЕ УДАЛЕНИЕ (Soft/Hard Delete)
### 6.1 Мягкое удаление роли "Редактор" (ID=5)
DELETE {{baseUrl}}/api/ref/policy/role/5/soft
Authorization: Bearer {{adminToken}}

### 6.2 Жесткое удаление роли "Редактор" навсегда
DELETE {{baseUrl}}/api/ref/policy/role/5
Authorization: Bearer {{adminToken}}